INSERT INTO sy_list (_key, _tx, area, id, title) VALUES 
	('sy.active', null, 'sy', 'active', 'Active'), 
	('sy.aggregation', null, 'sy', 'aggregation', 'Column Aggregation'), 
	('sy.duration', null, 'sy', 'duration', 'Duration'), 
	('sy.edit_type', null, 'sy', 'edit_type', 'Edit Type'),
	('sy.migration_status', null, 'sy', 'migration_status', 'Migration'), 
	('sy.msg_type', null, 'sy', 'msg_type', 'Message Type'), 
	('sy.node_attributes', null, 'sy', 'node_attributes', 'Node Attributes'), 
	('sy.search_oper_list_attr', null, 'sy', 'search_oper_list_attr', 'Search Operators (Attributes)'), 
	('sy.search_oper_list_boolean', null, 'sy', 'search_oper_list_boolean', 'Search Operators (Boolean)'), 
	('sy.search_oper_list_date', null, 'sy', 'search_oper_list_date', 'Search Operators (Date)'), 
	('sy.search_oper_list_keyword', null, 'sy', 'search_oper_list_keyword', 'Search Operators (Keywords)'), 
	('sy.search_oper_list_number', null, 'sy', 'search_oper_list_number', 'Search Operators (Number)'), 
	('sy.search_oper_list_option', null, 'sy', 'search_oper_list_option', 'Search Operators (Option)'),
	('sy.search_oper_list_radius', null, 'sy', 'searcy_oper_list_radius', 'Search Operators (Radius)'), 
	('sy.search_oper_list_scalar', null, 'sy', 'search_oper_list_scalar', 'Search Operators (Number and Date)'), 
	('sy.search_oper_list_subent', null, 'sy', 'search_oper_list_subent', 'Search Operators (Sub-Entity)'), 
	('sy.search_oper_list_text', null, 'sy', 'search_oper_list_text', 'Search Operators (Text)'), 
	('sy.week_days', null, 'sy', 'week_days', 'Days of the Week'), 
	('sy.wf_ntfcn_lvl', null, 'sy', 'wf_ntfcn_lvl', 'Workflow Notification Level'), 
	('sy.year', null, 'sy', 'year', 'Year'), 
	('sy.yesno', null, 'sy', 'yesno', 'Simple Yes or No');
